external_components:
  - source: github://vekexasia/comfoair-esp32
    components: [ comfoair ]

comfoair:
  id: comfo
  rx_pin: GPIO5
  tx_pin: GPIO4

esphome:
  name: comfoair
  friendly_name: comfoair

esp32:
  #board: esp32dev
  board: az-delivery-devkit-v4
  framework:
    type: arduino

#platform = espressif32


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR_KEY_GOES_HERE"

ota:
  password: "madrulez"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Comfoair Fallback Hotspot"
    password: "madrulez"

# see: https://esphome.io/components/time.html
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server
web_server:
  port: 80

button:
  - platform: template
    name: "Boost 10m"
    id: comfoair_boost_10min
    on_press:
      then:
        - lambda: |- 
            id(comfo).send_command("boost_10_min");

select:
  - platform: template
    name: "Belüftungsstärke"
    id: comfoair_ventilation_level
    optimistic: true
    options:
      - "Abwesend"
      - "Stufe 1"
      - "Stufe 2"
      - "Stufe 3"
    set_action:
      - lambda: |- 
          if (x == "Stufe 1") {
            id(comfo).send_command("ventilation_level_1");
          }
          if (x == "Stufe 2") {
            id(comfo).send_command("ventilation_level_2");
          }
          if (x == "Stufe 3") {
            id(comfo).send_command("ventilation_level_3");
          }
          if (x == "Abwesend") {
            id(comfo).send_command("ventilation_level_0");
          }
  - platform: template
    name: "Mode"
    id: comfoair_mode
    optimistic: true
    options:
      - "auto"
      - "manual"
    set_action:
      - lambda: |- 
          if (x == "auto") {
            id(comfo).send_command("auto");
          }
          if (x == "manual") {
            id(comfo).send_command("manual");
          }
